### ISSUE TITLE
Network statistics do not match with the objective function (constant included)

### ISSUE THREAD

**Issue by AlessandroPampado99** [PyPSA/PyPSA#1429]
### Version Checks (indicate both or one)

- [x] I have confirmed this bug exists on the lastest [release](https://github.com/pypsa/pypsa/releases) of PyPSA.

- [x] I have confirmed this bug exists on the current [`master`](https://github.com/pypsa/pypsa/tree/master) branch of PyPSA.

### Issue Description

After an optimization, I would expect that statistics capex+opex would match the objective function (+objective_constant). However, this does not always happen, as objective constant does not include the capital cost of the non extendable components, while statistics do.

The issue does not occur if all the components are extendable. 

### Reproducible Example

```python
import pypsa
import numpy as np
import pandas as pd

# --- Time span ---
snapshots = pd.date_range("2025-01-01", periods=24, freq="h")

# --- Network ---
n = pypsa.Network()
n.set_snapshots(snapshots)

# --- Bus ---
n.add("Bus", "bus0")

# --- Carriers ---
n.add("Carrier", "VRE")
n.add("Carrier", "slack")
n.add("Carrier", "battery")

# --- Load profile (MW): base + small variation ---
base_load = 100.0
daily_shape = 1.0 + 0.2*np.sin(2*np.pi*(snapshots.hour-8)/24)
p_set = base_load * daily_shape
n.add("Load", "load0", bus="bus0", p_set=pd.Series(p_set, index=snapshots))

# --- Variable generator (expandable) ---
solar_like = np.clip(np.sin(np.pi*(snapshots.hour-6)/12), 0, 1)
n.add(
    "Generator",
    "gen_var",
    bus="bus0",
    carrier="VRE",
    p_nom_extendable=True,     
    p_nom_min=0.0,
    p_max_pu=pd.Series(solar_like, index=snapshots),
    capital_cost=40.0,          
    marginal_cost=0.0,
)

# --- StorageUnit (fixed size, NOT expandable) ---
n.add(
    "StorageUnit",
    "storage0",
    bus="bus0",
    carrier="battery",
    p_nom=30.0,                
    max_hours=3.0,              
    p_nom_extendable=False,     
    efficiency_store=0.95,
    efficiency_dispatch=0.95,
    standing_loss=0.0,
    cyclic_state_of_charge=True,
    marginal_cost=0.0,
    capital_cost=1500.0,          
)

# --- Slack unit (very expensive) ---
n.add(
    "Generator",
    "slack",
    bus="bus0",
    carrier="slack",
    p_nom=1e6,                
    p_max_pu=1.0,
    marginal_cost=1e4,         
)

n.optimize(solver_name="gurobi")

stats = (n.statistics.capex().sum() + n.statistics.opex().sum()) / 1e6
obj = (n.objective + n.objective_constant) / 1e6
obj_const = n.objective_constant / 1e6
non_ext_cost = (n.storage_units.p_nom * n.storage_units.capital_cost).sum() / 1e6

stats - obj - (non_ext_cost - obj_const)
```

### Expected Behavior

(n.statistics.capex().sum() + n.statistics.opex().sum()) / 1e6
10.89201724937

Should match 

(n.objective + n.objective_constant) / 1e6
10.84701724936266

But it does not. This is because the constant objective is zero
n.objective_constant
0.0

While it should match 
(n.storage_units.p_nom * n.storage_units.capital_cost).sum() / 1e6
0.045

If you calculate the differences you get zero.
stats = (n.statistics.capex().sum() + n.statistics.opex().sum()) / 1e6
obj = (n.objective + n.objective_constant) / 1e6
obj_const = n.objective_constant / 1e6
non_ext_cost = (n.storage_units.p_nom * n.storage_units.capital_cost).sum() / 1e6

stats - obj - (non_ext_cost - obj_const) 
7.339837071462796e-12

### Installed Versions

<details>
name: pypsa2smspp
channels:
  - conda-forge
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - asttokens=3.0.0=pyhd8ed1ab_1
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2025.10.5=hbd8a1cb_0
  - certifi=2025.10.5=pyhd8ed1ab_0
  - comm=0.2.3=pyhe01879c_0
  - dask-core=2025.10.0=pyhcf101f3_0
  - debugpy=1.8.17=py311hc665b79_0
  - decorator=5.2.1=pyhd8ed1ab_0
  - exceptiongroup=1.3.0=pyhd8ed1ab_0
  - executing=2.2.1=pyhd8ed1ab_0
  - expat=2.7.1=h6a678d5_0
  - ipykernel=7.1.0=pyha191276_0
  - ipython=9.6.0=pyhfa0c392_0
  - ipython_pygments_lexers=1.1.1=pyhd8ed1ab_0
  - jedi=0.19.2=pyhd8ed1ab_1
  - jupyter_client=8.6.3=pyhd8ed1ab_1
  - jupyter_core=5.9.1=pyhc90fa1f_0
  - keyutils=1.6.3=hb9d3cd8_0
  - krb5=1.21.3=h659f571_0
  - ld_impl_linux-64=2.44=h153f514_2
  - libblas=3.9.0=38_h4a7cf45_openblas
  - libcblas=3.9.0=38_h0358290_openblas
  - libedit=3.1.20250104=pl5321h7949ede_0
  - libffi=3.4.4=h6a678d5_1
  - libgcc=15.2.0=h767d61c_7
  - libgcc-ng=15.2.0=h69a702a_7
  - libgfortran=15.2.0=h69a702a_7
  - libgfortran5=15.2.0=hcd61629_7
  - libgomp=15.2.0=h767d61c_7
  - liblapack=3.9.0=38_h47877c9_openblas
  - libnsl=2.0.0=h5eee18b_0
  - libopenblas=0.3.30=pthreads_h94d23a6_3
  - libsodium=1.0.20=h4ab18f5_0
  - libstdcxx=15.2.0=h8f9b012_7
  - libstdcxx-ng=15.2.0=h4852527_7
  - libuuid=1.41.5=h5eee18b_0
  - libxcb=1.17.0=h9b100fa_0
  - libzlib=1.3.1=hb25bd0a_0
  - linopy=0.5.8=pyhd8ed1ab_0
  - matplotlib-inline=0.2.1=pyhd8ed1ab_0
  - ncurses=6.5=h7934f7d_0
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - numpy=1.26.4=py311h64a7726_0
  - openssl=3.5.4=h26f9b46_0
  - parso=0.8.5=pyhcf101f3_0
  - pexpect=4.9.0=pyhd8ed1ab_1
  - pickleshare=0.7.5=pyhd8ed1ab_1004
  - pip=25.2=pyhc872135_1
  - prompt-toolkit=3.0.52=pyha770c72_0
  - psutil=7.1.2=py311haee01d2_1
  - pthread-stubs=0.3=h0ce48e5_1
  - ptyprocess=0.7.0=pyhd8ed1ab_1
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - python=3.11.14=h6fa692b_0
  - python_abi=3.11=2_cp311
  - pyzmq=27.1.0=py311h2315fbb_0
  - readline=8.3=hc2a1206_0
  - setuptools=80.9.0=py311h06a4308_0
  - sqlite=3.50.2=hb25bd0a_1
  - stack_data=0.6.3=pyhd8ed1ab_1
  - tk=8.6.15=h54e0aa7_0
  - tornado=6.5.2=py311h49ec1c0_1
  - traitlets=5.14.3=pyhd8ed1ab_1
  - typing_extensions=4.15.0=pyhcf101f3_0
  - wcwidth=0.2.14=pyhd8ed1ab_0
  - wheel=0.45.1=py311h06a4308_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - zeromq=4.3.5=h387f397_9
  - zlib=1.3.1=hb25bd0a_0
  - pip:
      - bottleneck==1.6.0
      - cachetools==6.2.1
      - cfgv==3.4.0
      - cftime==1.6.5
      - charset-normalizer==3.4.4
      - click==8.3.0
      - cloudpickle==3.1.1
      - colorama==0.4.6
      - contourpy==1.3.3
      - coverage==7.11.0
      - cycler==0.12.1
      - deprecation==2.1.0
      - distlib==0.4.0
      - et-xmlfile==2.0.0
      - filelock==3.20.0
      - fonttools==4.60.1
      - fsspec==2025.9.0
      - geopandas==1.1.1
      - google-api-core==2.28.1
      - google-auth==2.42.0
      - google-cloud-core==2.4.3
      - google-cloud-storage==3.4.1
      - google-crc32c==1.7.1
      - google-resumable-media==2.7.2
      - googleapis-common-protos==1.71.0
      - gurobipy==12.0.3
      - h5netcdf==1.7.3
      - h5py==3.15.1
      - highspy==1.12.0
      - identify==2.6.15
      - idna==3.11
      - importlib-metadata==8.7.0
      - iniconfig==2.3.0
      - jinja2==3.1.6
      - kiwisolver==1.4.9
      - levenshtein==0.27.1
      - locket==1.0.0
      - markupsafe==3.0.3
      - matplotlib==3.10.7
      - mypy==1.18.2
      - mypy-extensions==1.1.0
      - narwhals==2.10.0
      - ncompare==1.13.1
      - netcdf4==1.7.3
      - networkx==3.5
      - nodeenv==1.9.1
      - numexpr==2.14.1
      - openpyxl==3.1.5
      - packaging==25.0
      - pandas==2.3.3
      - partd==1.4.2
      - pathlib==1.0.1
      - pathspec==0.12.1
      - pillow==12.0.0
      - platformdirs==4.5.0
      - plotly==6.3.1
      - pluggy==1.6.0
      - polars==1.34.0
      - polars-runtime-32==1.34.0
      - pre-commit==4.3.0
      - proto-plus==1.26.1
      - protobuf==6.33.0
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.2
      - pydeck==0.9.1
      - pygments==2.19.2
      - pyogrio==0.11.1
      - pyparsing==3.2.5
      - pyproj==3.7.2
      - pypsa==1.0.2
      - pypsa2smspp==0.0.1
      - pysmspp==0.0.1
      - pytest==8.4.2
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - pyyaml==6.0.3
      - rapidfuzz==3.14.1
      - requests==2.32.5
      - rsa==4.9.1
      - scipy==1.16.3
      - seaborn==0.13.2
      - shapely==2.0.7
      - six==1.17.0
      - toolz==1.1.0
      - tqdm==4.67.1
      - tzdata==2025.2
      - urllib3==2.5.0
      - validators==0.35.0
      - virtualenv==20.35.4
      - xarray==2025.9.0
      - zipp==3.23.0
prefix: /dati/pampado/miniconda3/envs/pypsa2smspp</details>

**Comment by Irieo** [comment]
@AlessandroPampado99 I agree this is confusing; and fortunately this is solved with convenience of statistics module in PyPSA. 

If that's alright for everyone (and pinging @lkstrp and @fneum FYI), I close this issue; and provide explanation below.

https://github.com/PyPSA/PyPSA/blob/cd5d65b2a10ffbbf0e37f6e65c66151d259874d4/pypsa/optimization/optimize.py#L78-L366

The optimisation objective in PyPSA is deliberately structured to separate accounting (reporting) from the algebra solved by the LP/QP:

- n.objective contains OPEX plus the incremental CAPEX of extendable assets (achieved internally by charging CAPEX on the total p_nom_opt and subtracting the already‑built portion via the constant term).
- In the investment block, the model adds a CAPEX term proportional to the optimized nominal capacity (p_nom_opt) of extendables.
- The already‑built portion of those extendable capacities (their initial p_nom) is stored in n.objective_constant and subtracted from the model objective here: https://github.com/PyPSA/PyPSA/blob/cd5d65b2a10ffbbf0e37f6e65c66151d259874d4/pypsa/optimization/optimize.py#L176
- This nets out to paying only the incremental capacity inside n.objective.
- Existing non‑extendable assets’ CAPEX is not represented in either n.objective or n.objective_constant.
- Consequently, `n.objective + n.objective_constant` can differ from `n.statistics.capex() + n.statistics.opex()` whenever non‑extendable assets are present (their CAPEX appears only in the statistics).

It would be technically straightforward to also include non‑extendable CAPEX in the constant term, but doing so points toward a more general cost reporting layer. That broader, structured split is implemented in [statistics()](https://docs.pypsa.org/latest/user-guide/statistics/) module. For reporting, benchmarking, and economic interpretation you should rely on the statistics accessors (n.statistics.capex(), n.statistics.opex()), which reconstruct the right picture: existing + new extendable capacity costs, all non‑extendable capital costs, and operational costs with correct snapshot/investment weighting, as well as allow for easy filtering (existing vs. incremental vs. total CAPEX/OPEX) 

The objective_constant itself is rarely used, is super unintuitive (the subtraction pattern obscures intent), adds internal complexity for solver scaling, exists because it was added before statistics(),  and is most likely will be deprecated!

**Comment by FabianHofmann** [comment]
thanks @Irieo this makes all sense and actually I also forgot about this behavior! I still have the feeling we should tidy up and remove the objective_constant for good. it causes too much confusion rather than being helpful. I understand that it should point to the diff between previous and new installations, but the diff is then mixed up with the opex (and potential previous dispatch results are neglected)...  

with objective_constant removed, the only condition we rely on would be 

n.objective == n.stats.capex().sum() + n.stats.opex().sum()
